// สร้างอัตโนมัติจาก drop table ของมอนบอส (rewards/definitions/mobs.ts)
// boss card = card ของมอนที่ boss:true | boss gem = stat gem (ไม่ใช่ skill gem)
// แก้เพิ่ม/ลบเองได้ถ้าเจอที่จัดผิด

export const BOSS_CARDS: string[] = [
  "Alien Big Blink",
  "Angel Mage",
  "Bat Lord",
  "Cactus Boss",
  "Cat Bolt",
  "Death Mage",
  "Dragon Predator Robot",
  "Eyeball Monster",
  "Goblin Giant Gold",
  "Goblin Warchief",
  "Hare",
  "Hermit King",
  "Ice Mage",
  "Imp Devil",
  "Mega Ice Golem",
  "NightmareBerserkerBoss",
  "NightmareGunslingerBoss",
  "NightmareNecromancerBoss",
  "NightmarePaladinBoss",
  "NightmarePriestBoss",
  "NightmareShinobiBoss",
  "NightmareWizardBoss",
  "Queen Worm",
  "Scorpion King",
  "Snake Naga",
  "Spider Queen Robot",
  "Sting",
  "Sunflora Pixie",
  "Turtle King",
  "Werewolf",
  "Worm Creep",
  "Wraith",
  "Zombie Goblin King",
];

export const BOSS_GEMS: string[] = [
  "AtkSpd Gem",
  "CastSpd Gem",
  "CritDamage Gem",
  "CritDef Gem",
  "DefMult Gem",
  "Detector Gem",
  "DoubleAttack Gem",
  "Earth Gem",
  "Fire Gem",
  "Flee Gem",
  "Healing Gem",
  "Hit Gem",
  "Holy Gem",
  "HpMult Gem",
  "Leech Gem",
  "LeechMp Gem",
  "Matk Gem",
  "MdefMult Gem",
  "MoveSpd Gem",
  "MpCost Gem",
  "MpMult Gem",
  "NoCastCancel Gem",
  "NoFlinch Gem",
  "NoKnockback Gem",
  "PerfectCloak Gem",
  "Poison Gem",
  "ReflectDamage Gem",
  "ReflectSpell Gem",
  "Regen Gem",
  "Shadow Gem",
  "StatusResist Gem",
  "Threat Gem",
  "Undead Gem",
  "Water Gem",
  "WeightLimit Gem",
  "Wind Gem",
];
